title: Martin Quievre # your name (or website title) here
logo: "/images/Capture d’écran 2023-03-29 à 16.01.51.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a student of master Data Science for Business of École Polytechnique and HEC Paris
  <br><br>
  I'm interested in a lot of subjects from Data science, data analysis and web development. Previously at 
  Deepki, Ring Capital and Caisse des Dépots.
  <br><br>
  <a href="https://www.linkedin.com/in/martin-quievre/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
